### ISSUE TITLE
could you please add a method to add a property using extension witch using AssociatedObject 

### ISSUE THREAD

**Issue by michaelmou** [hyperoslo/Sugar#36]

**Comment by zenangst** [comment]
Hey @michaelmou, could you add a more in-depth description on what you need from this library so that we can probably evaluate it? From what I gather from the title, you want to be able to add properties at runtime using `AssociatedObject`.

Would you mind explaining what task you are trying to solve so we might understand you a tinsy bit better?

Also, there is nothing stopping you from creating a pull request of your own if you want to add additional features.

Cheers!

**Comment by michaelmou** [comment]
extension UITabBarController {

	private struct AssociatedKeys {
		static var ABC_TabBarControllerSingleTap = "ABC_TabBarControllerSingleTap"
        static var Yuko_TabBarControllerLastSelectIndex = "lastSelectIndex"
	}

	var signalOfSelectedIndexChanged: RACSignal? {
		get {
			return objc_getAssociatedObject(self, &AssociatedKeys.Yuko_TabBarControllerSingleTap) as? RACSignal
		}
		set {
			if let newValue = newValue {
				objc_setAssociatedObject(
					self,
					&AssociatedKeys.Yuko_TabBarControllerSingleTap,
					newValue as RACSignal?,
					objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC
				)
			}
		}
	}
    
    var lastSelectedIndex: Int? {
        get {
            return objc_getAssociatedObject(self, &AssociatedKeys.ABC_TabBarControllerLastSelectIndex) as? Int
        }
        set {
            if let newValue = newValue {
                objc_setAssociatedObject(
                    self,
                    &AssociatedKeys.ABC_TabBarControllerLastSelectIndex,
                    newValue as Int?,
                    objc_AssociationPolicy.OBJC_ASSOCIATION_ASSIGN
                )
            }
        }
    }

}

**Comment by michaelmou** [comment]
add a property through using extension

**Comment by michaelmou** [comment]
like this

**Comment by zenangst** [comment]
Hey @michaelmou, I don't think this is something that we will support any time soon as we don't have that need ourselves but feel free to make a pull request adding it  :sunglasses: 

Closing this one.
